name: Hello World

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: First step!
        run: echo "ğŸ‰ This is the first step!"
      - name: Second step!!
        run: echo "ğŸ‰ğŸ‰ This is the second step!!"
      - name: Third step!!!
        run: echo "ğŸ‰ğŸ‰ğŸ‰ This is the third step!!!"
      - name: Final step!!!!
        run: echo "ğŸ‰ğŸ‰ğŸ‰ğŸ‰ This is the fourth step!!!!"
